#!/usr/bin/env node
// Young Stoner Life dancers: new Tezzus and Diamond* sprites drawn on the original Power Calligraphy poses.
//   node tools/diamond-dancers.mjs
// The poses come from the original people cels (tools/lib/dancer-poses.mjs, one per cel), so the game plays
// the same animation with the same frame timing; the characters themselves are new: their own proportions,
// silhouettes and outfits, in the Rhythm Heaven GBA language (bold 1-pixel black outlines, flat colours,
// round mitt hands, big heads, chunky shoes).
// Drawn at 4x density (fine details: piercings, GG, tattoos, shades, scales) and reduced to a 1x occlusion mask.
// Writes public/skins/diamond-star/calligraphy/dancers.png, dancers@4x.png, dancers.json and
// reference/specs/power_calligraphy/diamond-dancers_preview.png.
import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { ROOT } from './lib/decomp.mjs';
import { Image } from './lib/png.mjs';
import { POSES } from './lib/dancer-poses.mjs';
import { CELL, D, diamond, tezzus } from './lib/dancer-art.mjs';

// ---------- sheet ----------
const COLS = 9, N = POSES.length;
const rgba = (s, a = 255) => ((parseInt(s.slice(1), 16) << 8) | a) >>> 0;
const sheet1 = new Image(COLS * CELL.w, Math.ceil(N / COLS) * CELL.h);
const sheet4 = new Image(COLS * CELL.w * D, Math.ceil(N / COLS) * CELL.h * D);
const PS = 2; // preview: detail sheet at 2x (8 px per game pixel)
const prev = new Image(COLS * CELL.w * D * PS, Math.ceil(N / COLS) * CELL.h * D * PS, rgba('#f4efe6'));
const cells = {};
for (let n = 0; n < N; n++) {
  const cv = n < 17 ? tezzus(POSES[n]) : diamond(POSES[n]);
  const name = `power_calligraphy_people_cel${String(n).padStart(3, '0')}`;
  const cx = (n % COLS) * CELL.w, cy = Math.floor(n / COLS) * CELL.h;
  cells[name] = { x: cx, y: cy, w: CELL.w, h: CELL.h, ax: CELL.ax, ay: CELL.ay, who: n < 17 ? 'tezzus' : 'diamond' };
  prev.rect(cx * D * PS, cy * D * PS, CELL.w * D * PS, CELL.h * D * PS, rgba('#c8c2b8'));
  for (let Y = 0; Y < cv.h; Y++)
    for (let X = 0; X < cv.w; X++) {
      const c = cv.px[Y * cv.w + X];
      if (!c) continue;
      sheet4.px[(cy * D + Y) * sheet4.w + cx * D + X] = rgba(c);
      prev.fill((cx * D + X) * PS, (cy * D + Y) * PS, PS, PS, rgba(c));
    }
  // 1x mask: a game pixel is covered if any of its detail pixels is; colour = the most common one
  for (let y = 0; y < CELL.h; y++)
    for (let x = 0; x < CELL.w; x++) {
      const count = new Map();
      for (let j = 0; j < D; j++) for (let i = 0; i < D; i++) { const c = cv.px[(y * D + j) * cv.w + x * D + i]; if (c) count.set(c, (count.get(c) ?? 0) + 1); }
      if (count.size) sheet1.px[(cy + y) * sheet1.w + cx + x] = rgba([...count].sort((a, b) => b[1] - a[1])[0][0]);
    }
  prev.text(cx * D * PS + 6, cy * D * PS + 6, String(n), rgba('#6b6560'), 4);
}
const out = join(ROOT, 'public', 'skins', 'diamond-star', 'calligraphy');
mkdirSync(out, { recursive: true });
writeFileSync(join(out, 'dancers.png'), sheet1.png());
writeFileSync(join(out, 'dancers@4x.png'), sheet4.png());
writeFileSync(
  join(out, 'dancers.json'),
  JSON.stringify({
    note: 'Young Stoner Life dancers (man cels -> Tezzus, woman cels -> Diamond*), new art on the original poses. Generated by tools/diamond-dancers.mjs.',
    sheet: 'dancers.png', detail: { sheet: 'dancers@4x.png', scale: D }, cells,
  }, null, 1) + '\n',
);
const specs = join(ROOT, 'reference', 'specs', 'power_calligraphy');
mkdirSync(specs, { recursive: true });
writeFileSync(join(specs, 'diamond-dancers_preview.png'), prev.png());
console.log('wrote', N, 'frames');
