// English for Karate Man's script text (our own translation of games/karate_man/karate_man_text.c).
export const KARATE_TEXT_EN: Record<string, string> = {
  D_0805ab50: "Your basics aren't there yet.",
  D_0805ab68: '',
  D_0805ab6c: 'Back-to-back punches seem to trip you up.',
  D_0805ab90: 'Your punch combos are razor sharp!',
  D_0805abb0: 'You nailed the finish!',
  D_0805abc4: "\nDon't forget to feel the beat!",
  D_0805abdc: "The Master's Words",
  D_0805abec: 'Welcome!\nThis is the Karate Man game.',
  D_0805ac0c: "All you do is punch things with the A button, but the timing is super strict.",
  D_0805ac60: "First, try punching the\nthings that fly at you,\nright on time!",
  D_0805aca0: "Well?\nGetting a feel for how\nstrict the timing is?",
  D_0805acd8: "Next, let's punch\nalong with the music!",
  D_0805ad04: "How was that?\nIsn't it easier when you ride the music?",
  D_0805ad38: "All right, like that —\nride the music and smack\nthose things around!",
  D_0805ad80: "\nThe real thing. Start!!",
  D_0805b3a8: "Your basics aren't there yet.",
  D_0805b3c4: '',
  D_0805b3c8: "You couldn't keep up with the fast parts.",
  D_0805b3e8: 'The fast parts were spot on!',
  D_0805b404: 'You got shaky in the slow parts.',
  D_0805b41c: 'Calm and steady in the slow parts!',
  D_0805b43c: 'I wish you had held back there...',
  D_0805b460: "Even super slow, you didn't flinch!",
  D_0805b480: "The Master's Words",
};
