// Hand looks for Power Calligraphy: extra pixels + palette changes painted into the original hand's tiles.
// The hand is 4bpp OBJ tiles on palette 11, which the charge glow fades to 12 and back from 13, so editing
// the tiles and those palettes (instead of swapping in raster art) keeps every frame and the glow working.
// Data: public/skins/<id>/calligraphy/hand.json + hand-overlay.png, generated by tools/diamond-hand.mjs.
import type { GameData } from '../../gba/assets';
import type { Cel } from '../../gba/ppu';
import type { RasterCel } from '../../gba/raster-cel';

export interface HandLookManifest {
  baseCel: string;
  origin: [number, number];
  overlay: string;
  colors: Record<string, number>; // overlay color (#rrggbb) -> palette index
  palettes: Record<string, Record<string, string>>; // OBJ palette -> index -> #rrggbb
}

const TILES = 'power_calligraphy_obj.4bpp';
const PALETTES = 'power_calligraphy_pal';
const HAND_ANIMS = ['brush', 'brush_still', 'brush_charge1', 'brush_charge2'];
const SKIN = new Set([3, 7]);
const SIZES = [
  [[8, 8], [16, 16], [32, 32], [64, 64]],
  [[16, 8], [32, 8], [32, 16], [64, 32]],
  [[8, 16], [8, 32], [16, 32], [32, 64]],
];

type Px = { entry: number; byte: number; hi: boolean; idx: number };

// Every OAM entry's pixels (transparent ones too), 2D OBJ mapping.
function layout(cel: Cel, tiles: Uint8Array) {
  const entries: Map<string, Px>[] = cel.map(([a0, a1, a2], entry) => {
    const px = new Map<string, Px>();
    const y0 = ((a0 & 0xff) << 24) >> 24, x0 = ((a1 & 0x1ff) << 23) >> 23;
    const [w, h] = SIZES[(a0 >> 14) & 3][(a1 >> 14) & 3];
    const hf = a1 & 0x1000, vf = a1 & 0x2000, tile = a2 & 0x3ff;
    for (let ty = 0; ty < h; ty++)
      for (let tx = 0; tx < w; tx++) {
        const sx = hf ? w - 1 - tx : tx, sy = vf ? h - 1 - ty : ty;
        const byte = (tile + (sy >> 3) * 32 + (sx >> 3)) * 32 + (sy & 7) * 4 + ((sx & 7) >> 1);
        const hi = (sx & 1) === 1;
        px.set(`${x0 + tx},${y0 + ty}`, { entry, byte, hi, idx: hi ? tiles[byte] >> 4 : tiles[byte] & 15 });
      }
    return px;
  });
  // Visible pixel = lowest OAM index that is opaque there.
  const visible = new Map<string, Px>();
  for (let e = entries.length - 1; e >= 0; e--) for (const [k, p] of entries[e]) if (p.idx) visible.set(k, p);
  const handEntries = new Set([...visible.values()].filter((p) => SKIN.has(p.idx)).map((p) => p.entry));
  return { entries, visible, handEntries };
}

export async function loadHandLook(data: GameData, url: string) {
  const manifest: HandLookManifest = await (await fetch(url)).json();
  const img = new Image();
  img.src = new URL(manifest.overlay, new URL(url, location.href)).href;
  await img.decode();
  const canvas = document.createElement('canvas');
  canvas.width = img.naturalWidth;
  canvas.height = img.naturalHeight;
  const ctx = canvas.getContext('2d', { willReadFrequently: true })!;
  ctx.drawImage(img, 0, 0);
  const rgba = ctx.getImageData(0, 0, canvas.width, canvas.height).data;

  const overlay: { x: number; y: number; idx: number }[] = [];
  for (let y = 0; y < canvas.height; y++)
    for (let x = 0; x < canvas.width; x++) {
      const i = (y * canvas.width + x) * 4;
      if (rgba[i + 3] < 128) continue;
      const hex = `#${[rgba[i], rgba[i + 1], rgba[i + 2]].map((v) => v.toString(16).padStart(2, '0')).join('')}`;
      const idx = manifest.colors[hex];
      if (idx === undefined) throw new Error(`hand overlay: color ${hex} at (${x},${y}) is not in hand.json colors`);
      overlay.push({ x: manifest.origin[0] + x, y: manifest.origin[1] + y, idx });
    }
  return applyHandLook(data, manifest, overlay);
}

export function applyHandLook(data: GameData, manifest: HandLookManifest, overlay: { x: number; y: number; idx: number }[]) {
  const src = data.bins[TILES];
  const tiles = src.slice();
  const baseCel = data.cels[manifest.baseCel];
  const base = layout(baseCel, src);
  // Sheet pixel -> base-frame position, to find how far each hand frame is shifted.
  const where = new Map<string, string>();
  for (const [k, p] of base.visible) if (SKIN.has(p.idx)) where.set(`${p.byte}:${p.hi}`, k);

  const handCels = new Set<Cel>();
  for (const a of HAND_ANIMS) for (const f of data.anims[`anim_power_calligraphy_${a}`] ?? []) handCels.add(f.cel);

  const written = new Map<string, number>();
  let conflicts = 0, uncovered = 0;
  for (const cel of handCels) {
    const L = cel === baseCel ? base : layout(cel, src);
    const votes = new Map<string, number>();
    for (const [k, p] of L.visible) {
      const b = SKIN.has(p.idx) && where.get(`${p.byte}:${p.hi}`);
      if (!b) continue;
      const [x, y] = k.split(',').map(Number), [bx, by] = b.split(',').map(Number);
      const d = `${x - bx},${y - by}`;
      votes.set(d, (votes.get(d) ?? 0) + 1);
    }
    const best = [...votes].sort((a, b) => b[1] - a[1])[0];
    if (!best) continue;
    const [dx, dy] = best[0].split(',').map(Number);
    for (const o of overlay) {
      const k = `${o.x + dx},${o.y + dy}`;
      let p = L.visible.get(k);
      if (p && !L.handEntries.has(p.entry)) continue; // the brush is in front here
      if (!p) {
        // transparent here: use the topmost hand entry that covers it
        const e = L.entries.findIndex((m, i) => L.handEntries.has(i) && m.has(k));
        if (e < 0) { uncovered++; continue; }
        p = L.entries[e].get(k)!;
      }
      const key = `${p.byte}:${p.hi}`;
      const prev = written.get(key);
      if (prev !== undefined && prev !== o.idx) { conflicts++; continue; }
      written.set(key, o.idx);
      tiles[p.byte] = p.hi ? (tiles[p.byte] & 0x0f) | (o.idx << 4) : (tiles[p.byte] & 0xf0) | o.idx;
    }
  }
  // Tiles we changed must not be used by anything but the hand.
  const touched = new Set([...written.keys()].map((k) => Math.floor(Number(k.split(':')[0]) / 32)));
  let shared = 0;
  for (const [name, cel] of Object.entries(data.cels)) {
    if (handCels.has(cel) || !name.startsWith('power_calligraphy_brush')) continue;
    for (const px of layout(cel, src).visible.values()) if (touched.has(Math.floor(px.byte / 32))) shared++;
  }
  if (conflicts || shared) console.warn(`hand look: ${conflicts} conflicting pixels, ${shared} pixels in tiles shared with other sprites`);

  const palettes = data.palettes[PALETTES].map((row, p) =>
    row.map((c, i) => {
      const hex = manifest.palettes[p]?.[i];
      return hex ? parseInt(hex.slice(1), 16) : c;
    }),
  );
  return { bins: { [TILES]: tiles }, palettes: { [PALETTES]: palettes }, stats: { pixels: written.size, conflicts, uncovered, shared } };
}

// Dancer looks: a sheet of 1x frames (dancers.png + dancers.json), one cell per original people cel.
// Each frame replaces its cel as raster art, anchored at the same sprite origin.
export async function loadDancerLook(data: GameData, url: string) {
  const manifest: {
    sheet: string;
    detail?: { sheet: string; scale: number };
    cells: Record<string, { x: number; y: number; w: number; h: number; ax: number; ay: number }>;
  } = await (await fetch(url)).json();
  const sheet = async (file: string) => {
    const img = new Image();
    img.src = new URL(file, new URL(url, location.href)).href;
    await img.decode();
    const canvas = document.createElement('canvas');
    canvas.width = img.naturalWidth;
    canvas.height = img.naturalHeight;
    const ctx = canvas.getContext('2d', { willReadFrequently: true })!;
    ctx.drawImage(img, 0, 0);
    return ctx;
  };
  const [ctx, dctx] = await Promise.all([sheet(manifest.sheet), manifest.detail ? sheet(manifest.detail.sheet) : null]);
  const S = manifest.detail?.scale ?? 1;
  const raster = new Map<Cel, RasterCel>();
  for (const [name, c] of Object.entries(manifest.cells)) {
    const cel = data.cels[name];
    if (!cel) throw new Error(`dancers.json: no cel ${name}`);
    const detail = dctx
      ? { scale: S, w: c.w * S, h: c.h * S, x0: -c.ax * S, y0: -c.ay * S, rgba: dctx.getImageData(c.x * S, c.y * S, c.w * S, c.h * S).data }
      : undefined;
    raster.set(cel, { w: c.w, h: c.h, x0: -c.ax, y0: -c.ay, rgba: ctx.getImageData(c.x, c.y, c.w, c.h).data, priority: 0, detail });
  }
  return raster;
}
